apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: first-pipeline # Executable ID (max length 64 lowercase-hyphen-separated), please modify this to any value if you are not the only user of your SAP AI Core instance. Example: `first-pipeline-1234`
  annotations:
    scenarios.ai.sap.com/description: "SAP AI Core"
    scenarios.ai.sap.com/name: "AI Core Tutorial"
    executables.ai.sap.com/description: "AI Core Greets the user"
    executables.ai.sap.com/name: "AI Core Hello Pipeline"
  labels:
    scenarios.ai.sap.com/id: "AI Core learning"
    ai.sap.com/version: "1.0"
spec:
  entrypoint: mypipeline
  templates:
  - name: mypipeline
    steps:
    - - name: greet
        template: greeter

  - name: greeter
    container:
      image: docker.io/python:latest
      command:
        - python3
        - '-c'
      args:
       - |
        print("Hello from SAP AI Core")
